language: cpp
notifications:
  email:
    recipients:
      - TomasFiedor@gmail.com
    on_success: always
    on_failure: always

compiler:
  - gcc
  - clang

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wget; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://www.brics.dk/mona/download/mona-1.4-17.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "oxs" ]]; then brew install http://www.brics.dk/mona/download/mona-1.4-17.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "oxs" ]]; then cd /usr/local; fi
  - if [[ "$TRAVIS_OS_NAME" == "oxs" ]]; then ls -al; fi
  - if [[ "$TRAVIS_OS_NAME" == "oxs" ]]; then find mona; fi

script:
  - make debug
  - make test
  - make release
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - clang++-3.8
      - libboost1.54-dev
      - libboost-system1.54-dev
      - libboost-filesystem1.54-dev
      - libboost-test1.54-dev
      - doxygen
      - flex
      - mona

cache: ccache

os:
  # - linux
  - osx

dist: trusty
