language: cpp
notifications:
  email:
    recipients:
      - TomasFiedor@gmail.com
    on_success: always
    on_failure: always

compiler:
  - gcc
  # - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # install GCC-4.9
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  # install Boost
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-test1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-test1.54.0_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-test1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-test1.54-dev_1.54.0-4ubuntu3_amd64.deb"
  - wget "http://cz.archive.ubuntu.com/ubuntu/pool/universe/m/mona/mona_1.4-15-1_amd64.deb" && sudo dpkg --install "mona_1.4-15-1_amd64.deb"

script:
  - make debug
  - make test
  - make release
  - make test

addons:
  apt:
    packages:
      - doxygen
      - flex

cache: ccache
