language: cpp
notifications:
  email:
    recipients:
      - TomasFiedor@gmail.com
    on_success: always
    on_failure: always

compiler:
  - gcc
  - clang

sudo: false

script:
  - make debug
  - make test
  - make release
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - clang++-3.8
      - libboost1.54-dev
      - libboost-system1.54-dev
      - libboost-filesystem1.54-dev
      - libboost-test1.54-dev
      - doxygen
      - flex
      - mona

cache: ccache

os:
  - linux

dist: trusty
